const path = require('path')
const del = require('del')
const Chance = require('chance')
const rw = require('rw')

const user = {}

module.exports = {
  before: function () {
    const userDataPath = path.resolve('tests/e2e/data/user.js')
    del.sync([userDataPath])
    const chance = new Chance()
    const name = chance.name().split(' ')
    user.username = name[0].toLowerCase() + chance.integer({min: 0, max: 1000000})
    user.email= user.username + '@e2e.space.com'
    user.password = 'password'

    let fileContent = '// This file is auto generated by ' + path.basename(__filename) + '\n'
    fileContent += '/* eslint-disable */\n'
    fileContent += 'module.exports = ' + JSON.stringify(user)
    fileContent += '\n/* eslint-enable */\n'
    rw.writeFileSync(userDataPath, fileContent, 'utf8')
  },
  'register page renders elements': function (browser) {
    const registerPage = browser.page.RegisterPage()
    console.log(registerPage)
    console.log(registerPage.url())
    console.log(registerPage
      .navigate().elements.app)

    registerPage
      .navigate()
      .verify.visible('@usernameInput')
      .waitForElementVisible('@app',5000)

      .verify.visible('@emailInput')
      .verify.visible('@passwordInput')
      .verify.visible('@submitButton')
      .verify.hidden('@formError')

    browser.end()
  },
  'register with incorrect data': function (browser) {
    const registerPage = browser.page.RegisterPage()
    registerPage
      .navigate()
      .register('', '', '')
    browser.assert.urlEquals(browser.launchUrl + 'register').end()
  },
  'register with correct data': function (browser) {
    const registerPage = browser.page.RegisterPage()
    registerPage
      .navigate()
      .register(user.username, user.email, user.password)
    browser.pause(5000)
    browser.assert.urlEquals(browser.launchUrl + 'login').end()
  }
}
